version: "3"

services:
  webserver:
    image: 78392/centos-php-apache:cap-0.1
    container_name: 'luffy-webserver'
    restart: 'on-failure'
    ports:
      - "80:80"
      - "443:443"
    links: 
      - mysql
    volumes: 
      - /opt/luffy/web:/var/www/html
      - /opt/luffy/php/php.ini:/usr/local/etc/php/php.ini
      - /opt/luffy/sites-enabled}:/etc/apache2/sites-enabled
      - /opt/luffy/logs/apache2}:/var/log/apache2
  mysql:
    image: mysql-server:5.7.25
    container_name: 'zoro-mysql'
    restart: 'always'
    ports:
      - "3306:3306"
    volumes: 
      - /opt/luffy/data/mysql}:/var/lib/mysql
      -/opt/luffy/logs/mysql}:/var/log/mysql
    environment:
      MYSQL_DATABASE: brook
      MYSQL_USER: chopper
      MYSQL_ROOT_PASSWORD: sanji
      MYSQL_PASSWORD: robin